---
- hosts: all
  become: yes
  tasks:
    # Установка Vim, Wget, Htop, Tmux
    - name: Install basic packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - wget
        - htop
        - tmux

    # Установка PHP 5.6
    - name: Install PHP 5.6
      apt_repository:
        repo: ppa:ondrej/php
        state: present
      when: ansible_distribution_release == 'jessie'
    - name: Install PHP 5.6 packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php5.6
        - php5.6-cli
        - php5.6-fpm
        - php5.6-mysql
        - php5.6-curl
        - php5.6-mbstring

    # Установка Nginx
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Configure Nginx
      template:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
      notify: restart